// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyrindketinzdlihuznm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55cmluZGtldGluemRsaWh1em5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTgzNDMsImV4cCI6MjA3MzQzNDM0M30.vI7gI2gXB7gwx6-a9fn5uwElFldv2JDJW0J_pT4jpgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});